### ISSUE TITLE
Add to readme.md

### ISSUE THREAD

**Issue by fariaslucas-mkt** [laiongabriel/bikcraft-origamid#1]
[Check it out.](https://laiongabriel.github.io/bikcraft-origamid/)

---

Obs.: No desktop o link pra page fica no canto direito, mas é sempre bom add no readme.md tbm, já que essa é a ordem natural de leitura.

**Comment by laiongabriel** [comment]
[https://c.tenor.com/TVrgcpGhWkIAAAAd/impressive-very-nice.gif](url)

**Comment by laiongabriel** [comment]
https://c.tenor.com/TVrgcpGhWkIAAAAd/impressive-very-nice.gif
